language: node_js
env:
  - CODECOV_TOKEN="2c31002d-d9f0-4f97-9215-10da9463d327"
node_js:
  - "10"
scripts:
  - npm install codecov -g
  - npm test
branches:
  only:
    - master
cache:
  directories:
    - "node_modules"
after_success:
  - codecov
